### ISSUE TITLE
这个项目怎么保持原项目更新同步呢？

### ISSUE THREAD

**Issue by Phrixus2023** [jianchang512/ChatTTS-ui#1]
如题

**Comment by jianchang512** [comment]
直接下载原项目的github代码覆盖就行

**Comment by qhgy** [comment]
用的win打包版 很方便 感谢
感觉默认的2个女声音色一般 不好听 这个要怎么自定义音色呢
另外源代码 和打包版结构不太一样呢 不知道覆盖哪个目录
再次感谢

**Comment by jianchang512** [comment]
https://github.com/2noise/ChatTTS
代码下载后有个 ChatTTS文件夹，本项目下也有个ChatTTS文件夹，覆盖就行


templates/index.html 打开，找到 <select ，<option value="2222">默认</option>

随意添加 option就行，value后的数字可以随意，随机获取音色，比如 3000  8000

**Comment by lin16303** [comment]
> https://github.com/2noise/ChatTTS 代码下载后有个 ChatTTS文件夹，本项目下也有个ChatTTS文件夹，覆盖就行
> 
> templates/index.html 打开，找到 <select ，默认
> 
> 随意添加 option就行，value后的数字可以随意，随机获取音色，比如 3000 8000

win打包版可以覆盖升级吗？
![QQ](https://github.com/jianchang512/ChatTTS-ui/assets/130566478/7ac72b23-98ca-4100-ba75-a34ce991ae46)

**Comment by jianchang512** [comment]
> 不可
这个后续使用新的打包版升级

**Comment by qhgy** [comment]
加油 感谢(^🙏^)
