### ISSUE TITLE
有没有办法把它装到Windows的TTS内？

### ISSUE THREAD

**Issue by msjsc001** [jianchang512/ChatTTS-ui#120]
大佬你好，有没有办法把它装到Windows的TTS内？因为现在系统默认的这些TTS都太糟糕。
这样就能提供给 Balabolka、win11放大镜、Anki插件AwesomeTTS使用。
![image](https://github.com/jianchang512/ChatTTS-ui/assets/93178788/cba0ff7e-65e9-4143-9c4b-a8e88783e1cd)
![image](https://github.com/jianchang512/ChatTTS-ui/assets/93178788/97bf7907-6589-436f-9bc4-4b75ec0e2993)
![image](https://github.com/jianchang512/ChatTTS-ui/assets/93178788/44bb6740-fc48-4310-9d6d-9500df80bd9d)

**Comment by jianchang512** [comment]
无
