### ISSUE TITLE
AMD显卡问题

### ISSUE THREAD

**Issue by yangda611** [jianchang512/ChatTTS-ui#134]
详情问一下这个项目不支持AMD显卡吗，我看拿CPU硬算起来了
![image](https://github.com/jianchang512/ChatTTS-ui/assets/75526029/9308affe-4a68-4f2c-aedb-737f8df53fb0)
![image](https://github.com/jianchang512/ChatTTS-ui/assets/75526029/a692eba6-bc94-4327-ae5d-e1d90e76110e)

**Comment by MarkLily** [comment]
我的也一样，你看首页，https://github.com/jianchang512/ChatTTS-ui 有一部分需要设置的
