### ISSUE TITLE
BUG:长文本的音色是乱的，不固定

### ISSUE THREAD

**Issue by louyongjiu** [jianchang512/ChatTTS-ui#136]
长文本的音色是乱的，不固定

**Comment by jianchang512** [comment]
1. 多长的文本
2. 结果是几个音色

截图使用的各项配置，粘贴使用的全部文本

**Comment by louyongjiu** [comment]
<img width="1054" alt="1718466149539" src="https://github.com/jianchang512/ChatTTS-ui/assets/16408477/c8856f8a-30ff-444e-8778-d69e275d9876">
有2种音色 以下是全部文本
你听说过《小王子》吗？这可是一本让大人们也会泪目的童话书哦！小王子这个小小的外星旅行者，用他那双纯真的眼睛，让我们重新审视了爱、友情与生活的意义。书中那个爱上玫瑰花的小王子，总是让人忍不住想说：哎呀，小王子，你怎么这么可爱！如果你觉得自己的生活有点单调无趣，那么快来翻开这本书吧！你会发现，原来我们每个人心中都住着一个小王子，他在提醒我们：重要的东西是看不见的。读完这本书，你可能会想去找一颗属于自己的小行星，或者至少，会想给你的玫瑰花多浇点水。总之，这本书绝对值得你一读再读，因为它会让你笑中带泪，泪中带笑！

**Comment by louyongjiu** [comment]
[224828_use53.81s-audio47.45s-seed99999-te1e-05-tp0.7-tk20-textlen255-99635.zip](https://github.com/user-attachments/files/15848434/224828_use53.81s-audio47.45s-seed99999-te1e-05-tp0.7-tk20-textlen255-99635.zip)
生成的音频文件

**Comment by louyongjiu** [comment]
音色有轻微的差别  感觉像是声音大小不同

**Comment by jianchang512** [comment]
音调发生变化，这个ChatTTS本身就存在，为了适应长文本，会自动将期按照150-200字数分割为多行，然后批量推理。虽然参数相同，但每次推理音色都会有微小变化，也就是音色无法非常稳定。
