### ISSUE TITLE
prompt: str| 可选，默认 空， 设定 笑声、停顿，例如 [oral_2][laugh_0][break_6]  这个怎么用

### ISSUE THREAD

**Issue by anstonjie** [jianchang512/ChatTTS-ui#137]
比如我输入的是： 欢迎大家来到美丽的宇宙中今天我一天 特别开心哈哈哈，你们也一定要来呀

我想让他在 哈哈哈 处笑出来 应该怎么设置 prompt 谢谢

**Comment by jianchang512** [comment]
text="你好啊[uv_break]朋友们,听说今天是个好日子,难道[uv_break]不是吗[laugh]？"

在实际合成中，[laugh] 将被笑声替代，[uv_break] 处将加入停顿。
对于笑声 停顿的强度和随机插入的数量，可通过参数 params_refine_text中传递 prompt 控制。
laugh_(0-2) 可选值： laugh_0 laugh_1 laugh_2
break_(0-7) 可选值:  break_0 break_1 break_2 break_3 break_4 break_5 break_6 break_7
