### ISSUE TITLE
并发转换慢

### ISSUE THREAD

**Issue by weizhoujie** [jianchang512/ChatTTS-ui#141]
测试单个请求5s，20并发平均值100多s，机器资源也没多少占用
![image](https://github.com/jianchang512/ChatTTS-ui/assets/49552532/009099ab-4de1-4b61-b18d-3e0f6041ac46)
![image](https://github.com/jianchang512/ChatTTS-ui/assets/49552532/8886f384-a0a6-4e76-9ba0-282487feab07)
队列似乎也不应该变得这么慢

**Comment by weizhoujie** [comment]
单个任务速度30it/s，两个任务15it/s，似乎刚好腰斩，显存上涨也不大，这是为何呢

**Comment by jianchang512** [comment]
并发无意义，瓶颈在gpu

**Comment by weizhoujie** [comment]
![Uploading image.png…]()

**Comment by weizhoujie** [comment]
8G显存还没占满
![image](https://github.com/jianchang512/ChatTTS-ui/assets/49552532/927eed59-1101-4bcc-89b0-5d15461ec9ca)

**Comment by li2233-max** [comment]
哥，你是怎么做的并发测试

**Comment by DesertSpring** [comment]
我的内容很少，2-3秒的内容，一个一个来差不多2-6秒一个文件，如果同时发送7个文件，第三个开始一直重复处理，全部生产完成需要好几分钟，而且正常情况下，7个任务生产14个文件，如果是并发情况，7个任务会生产几十个重复文件，已经排除API接口重复调用的问题。我的实际场景是每隔一秒向CHATTTS发送一个任务请求，现在修改为同时执行两个，如果前两个没有返回，就不发送任务。我现在的问题是 音频时长为-1。
