### ISSUE TITLE
Linux centos7部署docker cpu版请求超时

### ISSUE THREAD

**Issue by suchan66** [jianchang512/ChatTTS-ui#148]
**报错内容如下：**
error="git was not found in the system: exec: \"git\": executable file not found in $PATH"
failed to solve: pytorch/torchserve:0.11.0-cpu: failed to resolve source metadata for docker.io/pytorch/torchserve:0.11.0-cpu: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/83/8391271abb7a75ece2ed9528ff9ed1565e970ac5a901ef5fc15d8ae7974e2e7b/data?verify=1719217323-l%2FRDny5H042jWJvTDRGaczVIZxE%3D": dial tcp 179.60.193.16:443: i/o timeout

**报错截图如下：**
![image](https://github.com/jianchang512/ChatTTS-ui/assets/30565066/ee40040f-ed7b-4e7d-922a-d365be570860)

**Comment by jianchang512** [comment]
网络问题，连不上docker 挂梯子
