### ISSUE TITLE
长文本句分行后，语音在分行连接处，音色明显感觉有点不同

### ISSUE THREAD

**Issue by liuyanqun0815** [jianchang512/ChatTTS-ui#149]
将文本按照特殊符号切大于某个长度进行换行，我看代码会将text文本转成list， 设置的音色是一个，底层代码是并发执行的吧
最后将语音合并到一个地址里面，连接处的音色有点不同这个有没有好的办法呢？

**Comment by jianchang512** [comment]
目前没有好办法，不管是list批量合成，或者截断后多次合成，音色多少都会存在差异，而单次单批合成超过200字会吞字，等待ChatTTS优化吧

**Comment by zhcngh** [comment]
使用女声音色，有音色变化能接受，但突然来个男声， 我正在卖凶兆呢。。

**Comment by jianchang512** [comment]
升级0.95
