### ISSUE TITLE
为啥换不同的Voice都是一样的，换文字就随机生成音色

### ISSUE THREAD

**Issue by land007** [jianchang512/ChatTTS-ui#152]
![image](https://github.com/jianchang512/ChatTTS-ui/assets/574543/a6391bd8-43e3-4db0-b3f1-3a61cb98c21c)

**Comment by jianchang512** [comment]
下载 0.95 补丁包覆盖

**Comment by land007** [comment]
谢谢，获取了最新代码并制作成镜像，现在稳定了。
