### ISSUE TITLE
使用了pt文件，可是音色还是随机的，求救

### ISSUE THREAD

**Issue by younger027** [jianchang512/ChatTTS-ui#153]
当前ui版本是0.93，从speaker那边下载了pt文件到speaker目录，明确看日志确实使用的pt，可是多点击几次生成，音色不固定。而且是男女的不固定。求救xdm。
如图：生成出来三句，每一句都不一样的音色
![image](https://github.com/jianchang512/ChatTTS-ui/assets/14865571/ea5116d2-e49e-410c-836c-583264e4f802)
执行的log如下:
![image](https://github.com/jianchang512/ChatTTS-ui/assets/14865571/e0b9b2bb-f687-40e6-a606-b871a9b00ec7)

**Comment by younger027** [comment]
我好像发现问题了，目前看起来这个pt文件是和中文绑定的，我的text如果是英文的话，生成的声音就是随机的

**Comment by jianchang512** [comment]
重新 git pull代码。

**Comment by younger027** [comment]
目前ok了，感谢回复
