### ISSUE TITLE
生成没有报错，但是播放全是杂音

### ISSUE THREAD

**Issue by vanish1984** [jianchang512/ChatTTS-ui#154]
<img width="1709" alt="image" src="https://github.com/jianchang512/ChatTTS-ui/assets/2005160/11fb57fc-2816-43d2-ae12-970da3ee86d9">

如题
Mac M2 
MacOS 14.4.1
源码部署

**Comment by vanish1984** [comment]
换过不同音色，都是杂音

**Comment by vanish1984** [comment]
![image](https://github.com/jianchang512/ChatTTS-ui/assets/2005160/e17538aa-9fff-4a8d-82c8-2f96d01f03b5)

**Comment by tjglfglf** [comment]
遇到了一样得问题，m1

**Comment by jianchang512** [comment]
如果不是 0.95，就先重新git pull拉取新代码

如果已是，请安装 ChatTTS 官方代码测试  https://github.com/2noise/ChatTTS   貌似 ChatTTS内部问题

**Comment by jianchang512** [comment]
如果不是 0.95，就先重新git pull拉取新代码

如果已是，请安装 ChatTTS 官方代码测试  https://github.com/2noise/ChatTTS   貌似 ChatTTS内部问题

**Comment by vanish1984** [comment]
今天更新代码后恢复正常，谢谢。
