### ISSUE TITLE
启动有报错

### ISSUE THREAD

**Issue by liuyanqun0815** [jianchang512/ChatTTS-ui#173]
代码更新到最新后，启动项目有报错
use default LlamaModel for importing TELlamaModel error: No module named 'transformer_engine'，启动完了。
通过webUI ，输入文本带换行符的，底层没有并发处理呢？
![image](https://github.com/jianchang512/ChatTTS-ui/assets/31815712/0886e418-42cc-4b62-9319-2deaacfaf4b4)

**Comment by jianchang512** [comment]
本就无并发
之前有批量，现取消了，一次合成一行
