### ISSUE TITLE
这是是什么问题？

### ISSUE THREAD

**Issue by z3623556z** [jianchang512/ChatTTS-ui#191]
![image](https://github.com/user-attachments/assets/5ef5c3ef-3e10-47b8-8c38-61b2229a30d6)

**Comment by z3623556z** [comment]
已解决

**Comment by OnlyFlashEobard** [comment]
> 已解决

请问后来怎么解决的

**Comment by jianchang512** [comment]
不要使用以前的pt文件，重新传入音色值新生成，chatTTS升级后以前的pt文件无法直接使用
