### ISSUE TITLE
windows 源码部署提示要安装ffmpeg

### ISSUE THREAD

**Issue by alterem** [jianchang512/ChatTTS-ui#198]
![image](https://github.com/user-attachments/assets/ed29d8b8-0971-43c8-a002-b36db8254bc7)

![image](https://github.com/user-attachments/assets/ad3f334e-fa50-426b-88fd-a2db8bde03d9)

**Comment by shenxuzaier** [comment]
去ffmpeg官网下载软件，然后解压到C:\ffmpeg，然后把C:\ffmpeg\bin添加到系统变量PATH里就好了

**Comment by jianchang512** [comment]
打开 app.py 

14行开始这几行代码删掉

![image](https://github.com/user-attachments/assets/32bbaef9-14a0-43f5-a5ea-65ff23c9814a)

**Comment by whille** [comment]
我想是win下app.exe找不到ffmpeg.exe，path问题，可以把ffmpeg.exe从ffmpeg目录下移动到上一层就行

**Comment by alterem** [comment]
需要配置环境变量
