### ISSUE TITLE
Ubuntu 20.04 下容器部署 一键部署，报错

### ISSUE THREAD

**Issue by winposs** [jianchang512/ChatTTS-ui#233]
**环境：
ARM 架构 Ubuntu 20.04
4G24核内存
刚刚重装的干净系统**

执行 `docker-compose -f docker-compose.cpu.yaml up -d` 的时候报错如图：

![1111](https://github.com/user-attachments/assets/a4158720-7f0d-477e-9082-c07ed0ea4260)

请问是不是ARM无法安装啊？

**Comment by jianchang512** [comment]
不支持

**Comment by winposs** [comment]
> 不支持

我这个ARM64 架构，Ubuntu 20.04，4G CPU 24核内存，源码安装可以用吗？

**Comment by 421333** [comment]
Ubuntu 20.04采用镜像部署也出现类似问题
![image](https://github.com/user-attachments/assets/4a0b25c3-729d-48e1-81df-29c87e41acc1)

**Comment by lucasmen9527** [comment]
> Ubuntu 20.04采用镜像部署也出现类似问题 ![image](https://github.com/user-attachments/assets/4a0b25c3-729d-48e1-81df-29c87e41acc1)

这个我今天部署的时候也遇到了 docker compose问题 你先试试运行docker compose version 看看有没有版本 我用的腾讯云的hai gpu服务器 自带的docker 执行的时候 发现没这个命令 就重新安装了下 重新安装完就可以了
