### ISSUE TITLE
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead

### ISSUE THREAD

**Issue by EvanMei1985** [jianchang512/ChatTTS-ui#24]
2024-06-01 00:48:11,055 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-06-01 00:48:11,056 - modelscope - INFO - Loading ast index from C:\Users\XXX\.cache\modelscope\ast_indexer
2024-06-01 00:48:11,121 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 533195b467ca2616b63b56949f55fd59 and a total number of 976 components indexed
INFO:ChatTTS.core:Load from local: D:/XXX/chatTTS-ui/models\pzc163\chatTTS
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
启动:['127.0.0.1', '9966']

Guys, any others met the same issue?

**Comment by jianchang512** [comment]
It's not reporting an error, it's just suggesting that the current device can't use GPU acceleration and has to use the CPU.

If you want GPU acceleration, you need an NVIDIA card with cuda11.8+ installed.

**Comment by EvanMei1985** [comment]
> It's not reporting an error, it's just suggesting that the current device can't use GPU acceleration and has to use the CPU.
> 
> If you want GPU acceleration, you need an NVIDIA card with cuda11.8+ installed.

Thanks for reply!

Sorry I didn't provide enough information...

(venv) D:\AI-Tool\chatTTS-ui>nvcc    --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

Thank you again...

**Comment by EvanMei1985** [comment]
I fixed the issue by using: pip install torch torchvision torchaudio  --index-url https://download.pytorch.org/whl/cu118
![image](https://github.com/jianchang512/ChatTTS-ui/assets/137168518/3f646bb9-0950-4cad-b9ae-95d5a98bc1e0)
