### ISSUE TITLE
No GPU found, use CPU instead

### ISSUE THREAD

**Issue by WavesMan** [jianchang512/ChatTTS-ui#35]
CUDA版本12.4
已参考教程安装Cuda工具、cudnn仍然无法使用GPU
日志：
2024-06-01 22:30:31,792 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-06-01 22:30:31,793 - modelscope - INFO - Loading ast index from C:\Users\diwei\.cache\modelscope\ast_indexer
2024-06-01 22:30:31,922 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 bcc4b501ab7f96fbbf904df1563439ec and a total number of 976 components indexed
INFO:ChatTTS.core:Load from local: D:/Another APP/Chat-TTS/chatTTS-ui/models\pzc163\chatTTS
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
启动:['127.0.0.1', '9966']

**Comment by jianchang512** [comment]
源码部署还是预打包版，源码的话必须 安装 torch cuda版。仔细看仓库说明页面 Windows源码部署说明

**Comment by WavesMan** [comment]
是源码部署，但是已经安装了torch还是报not gpu

**Comment by jianchang512** [comment]
需要安装gpu版的torch

首先执行下 `pip uninstall -y torch torchaudio`

如果你的cuda是11.x 执行这个

`pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu118`

如果是 12.x 执行这个
`pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu121`

**Comment by BoosterCore** [comment]
![Screenshot 2024-06-02 150651](https://github.com/jianchang512/ChatTTS-ui/assets/73834045/487792ea-64a4-41af-962d-9a848e5d4d57)
是不是不支持 12.5 ？我这边 执行了 pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu121 ，但任然提示找不到GPU，环境变量也确认设置好的。

**Comment by jianchang512** [comment]
先卸载再重装试试

`pip uninstall -y torch torchaudio`

然后再安装

**Comment by BoosterCore** [comment]
> 先卸载再重装试试
> 
> `pip uninstall -y torch torchaudio`
> 
> 然后再安装

感谢，感谢，这方法管用！

**Comment by CrazyBunQnQ** [comment]
我也遇到了...最开始安的 cu121，不好使，看驱动时 11.8 就卸载重装了 cu118 的一套，还是不行啊...啥情况啊
![image](https://github.com/jianchang512/ChatTTS-ui/assets/17765748/dbda9ef6-0c41-457c-975d-78a73c120f8b)

**Comment by jianchang512** [comment]
nvcc --version 看看

**Comment by CrazyBunQnQ** [comment]
> nvcc --version 看看

倒数第二个命令输出了

**Comment by jianchang512** [comment]
尝试更新下显卡驱动

**Comment by CrazyBunQnQ** [comment]
> 尝试更新下显卡驱动

刚更新完，还是不行...我发现我现在 Conda 所有的虚拟环境都识别不到 GPU 了...我的天...

**Comment by Captain0X** [comment]
同样的问题，我解决了，卸载重装，
pip uninstall -y torch torchaudio
我的显卡是CUDA Version: 12.7
安装的时候最好设置下代理，不然几个G很慢。
python -m pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu121 --proxy socks5://127.0.0.1:7890
最终：
![Image](https://github.com/user-attachments/assets/b6f6866f-0807-4431-8a85-6f50c2ea7eca)
