### ISSUE TITLE
Mac Python3 app.py 运行报错

### ISSUE THREAD

**Issue by shog86** [jianchang512/ChatTTS-ui#4]
第一次运行安装到某个模块时下载速度为0，所以关掉开了全局又来一次，结果报错

/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by jianchang512** [comment]
brew install openssl@1.1

pip install urllib3=1.26.15


然后再重新安装一遍依赖。

**Comment by shog86** [comment]
提示应该是两个==，多谢~
