### ISSUE TITLE
打包版中如何使用cuda

### ISSUE THREAD

**Issue by Chenyuxin221** [jianchang512/ChatTTS-ui#50]
装了cuda12.5 仍然显示
![image](https://github.com/jianchang512/ChatTTS-ui/assets/86191513/99a1cf4a-8b2b-401b-a1e1-cc24bb5884a7)
是需要特定的版本吗？还是说需要额外的操作

**Comment by jianchang512** [comment]
use cuda:0 就是使用了cuda

**Comment by Chenyuxin221** [comment]
> use cuda:0 就是使用了cuda

好的
