### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Chenyuxin221** [jianchang512/ChatTTS-ui#52]
![image](https://github.com/jianchang512/ChatTTS-ui/assets/86191513/7f1a415f-2715-48a9-9a16-e668120534a7)
cuda版本12.5
python版本3.12.3

**Comment by jianchang512** [comment]
常见问题都有说明，而且这报错也很明显啊，不支持 3.12，降低python版本到3.10

**Comment by Chenyuxin221** [comment]
> 常见问题都有说明，而且这报错也很明显啊，不支持 3.12，降低python版本到3.10

好的

**Comment by Chenyuxin221** [comment]
> 常见问题都有说明，而且这报错也很明显啊，不支持 3.12，降低python版本到3.10

![image](https://github.com/jianchang512/ChatTTS-ui/assets/86191513/dda2a59b-9e42-4f7c-a7d9-a690930212ec)
悲 新的问题

**Comment by jianchang512** [comment]
源码部署？重新拉取代码，然后 打开 .env，将compile=true的true改成false

**Comment by Chenyuxin221** [comment]
> pip install torch torchaudio --index-url [https://download.pytorch.org/whl/cu121 ](https://download.pytorch.org/whl/cu121%C2%A0)

成功启动 但是报错，在跑了应该不影响吧？
![image](https://github.com/jianchang512/ChatTTS-ui/assets/86191513/a5982827-f4b2-4770-ab03-ab8e0870f69c)

**Comment by jianchang512** [comment]
.env打开，将 compile=true 改为 compile=false

**Comment by Chenyuxin221** [comment]
> .env打开，将 compile=true 改为 compile=false

最新版本首次合成报错
![image](https://github.com/jianchang512/ChatTTS-ui/assets/86191513/beb10305-f920-4ed2-a9d9-d8079a219192)

**Comment by jianchang512** [comment]
打开 .env 将 compile=true 改成 compile=false 试试

**Comment by Chenyuxin221** [comment]
> 打开 .env 将 compile=true 改成 compile=false 试试

最新版本默认就是false 奇怪的问题
