### ISSUE TITLE
feat(app): async router

### ISSUE THREAD

**Issue by QIN2DIM** [jianchang512/ChatTTS-ui#53]
Do you consider switching to Fastapi asynchronous interface?

For example, you can use the coroutine queue to handle tasks. In this way, the page will not be blocked when generating audio files

**Comment by jianchang512** [comment]
This type of task usually does not have several concurrency, even most of them are single request, flask + waitress is enough, and waitress is pure py, simple/compatible, in contrast, there is no need to add complexity to introduce asynchronous
