### ISSUE TITLE
feat(pyproject.toml): stable requirements

### ISSUE THREAD

**Issue by QIN2DIM** [jianchang512/ChatTTS-ui#54]
可以考虑使用 pyproject.toml 管理项目依赖，整个项目的依赖树看的我头都大了。

比如，`vocos` 的依赖项包括了 torch，那么直接 `pip install -r req.txt` 就会拉下来vocos 以及 CPU 版的 torch，那么后续再单独运行带有 `--index-url` flag 的指令就不起作用了（因为对应的依赖已经拉到当前环境里了），还需要额外的 `--ignore-installed` 才能覆盖下载。

同样的情况，如果使用 `uv` 或者 `pdm` 执行的指令也不一样，例如覆盖安装需要 `uv pip install torch -i [url] --reinstall`。

所以不如一开始就用 pyproject.toml 管理依赖，头大。

**Comment by QIN2DIM** [comment]
只能说太逆天了，两个仓库的 issues 统计起来有超过一半的问题全是关于怎么 pip install 的。

**Comment by jianchang512** [comment]
python老问题了，几乎任意和使用venv+pip的项目都会很多依赖问题，主要venv pip 是python自带，简单通用，多数还是用的这个
