### ISSUE TITLE
[Question]: tqdm progress

### ISSUE THREAD

**Issue by QIN2DIM** [jianchang512/ChatTTS-ui#56]
![image](https://github.com/jianchang512/ChatTTS-ui/assets/62018067/f8567f03-a2fa-4487-bef2-64b41782ceb8)

源码我还没时间细看，但进度条要么是统计的口径有问题，要么是提前跳出了。但似乎是上游项目的问题

**Comment by jianchang512** [comment]
是的。chatTTS
