### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ZhhHugoChang** [jianchang512/ChatTTS-ui#58]
![微信截图_20240603110858](https://github.com/jianchang512/ChatTTS-ui/assets/30371886/a7a5ef5a-7b7e-40e3-950f-e5fd3b306c60)

**Comment by rookie0peng** [comment]
朋友，你是不是开VPN了，我的报错和你一样，把VPN关了就好了

**Comment by jianchang512** [comment]
modelscope.cn 不允许国外ip下载。关闭代理，仓库说明页面也有些

**Comment by ZhhHugoChang** [comment]
> 朋友，你是不是开VPN了，我的报错和你一样，把VPN关了就好了

感谢

**Comment by ZhhHugoChang** [comment]
> modelscope.cn 不允许国外ip下载。关闭代理，仓库说明页面也有写

thanks
