### ISSUE TITLE
克隆之后找不到requirements.txt

### ISSUE THREAD

**Issue by shog86** [jianchang512/ChatTTS-ui#6]
FVFHR4N9Q05N:chattts user$ pip3 install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

但在chattts下面已经有了chatTTS-ui的所有文件

**Comment by jianchang512** [comment]
可能是目录错了
找到这个txt目录，进去再安装
