### ISSUE TITLE
mac 安装不了soundfile

### ISSUE THREAD

**Issue by bigpin** [jianchang512/ChatTTS-ui#60]
import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'

但是安装soundfile：
pip install soundfile                                                   11:38:21

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: soundfile in /Users/dingli/Library/Python/3.9/lib/python/site-packages (0.12.1)
Requirement already satisfied: cffi>=1.0 in /Users/dingli/Library/Python/3.9/lib/python/site-packages (from soundfile) (1.16.0)
Requirement already satisfied: pycparser in /Users/dingli/Library/Python/3.9/lib/python/site-packages (from cffi>=1.0->soundfile) (2.22)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.9 -m pip install --upgrade pip

**Comment by jianchang512** [comment]
再运行试试，看起来是安装成功了
要注意是在同一个虚拟环境下运行

**Comment by jianchang512** [comment]
先执行 brew install libsndfile

再执行 pip install soundfile

**Comment by bigpin** [comment]
可以了，之前在vscode里面的终端安装不太行，系统里面直接运行就行
