### ISSUE TITLE
macOS 执行app.py报错 FileNotFoundError

### ISSUE THREAD

**Issue by 66coder66** [jianchang512/ChatTTS-ui#80]
macOS 执行app.py报错 FileNotFoundError: [Errno 2] No such file or directory: '../ChatTTS-ui/models/pzc163/chatTTS/config/path.yaml' (venv)
![Uploading 截屏2024-06-04 17.02.56.png…]()

**Comment by jianchang512** [comment]
似乎模型不完整，重新下载模型或者 打开 https://www.modelscope.cn/models/pzc163/chatTTS/files   下载 path.yaml  、复制到上图报错里显示的文件夹内 ChatTTS-ui/models/pzc163/chatTTS/config/
