### ISSUE TITLE
#macOS version install error#

### ISSUE THREAD

**Issue by humbleAna** [jianchang512/ChatTTS-ui#81]
git commit hash e428361e316d18e53985b630eacf2e6c4347be72
ERROR: Could not find a version that satisfies the requirement torch==2.1.2 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0)
ERROR: No matching distribution found for torch==2.1.2

1 i try to install the version 2.2.0
2 then it  mention
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xx/Desktop/data/chattts/chatTTS-ui/models/pzc163/chatTTS/config/path.yaml'
 what happend bro

**Comment by jianchang512** [comment]
#80
